version: "3.7"

services:
  solar:
    build: ./solar
    restart: always
    expose:
      - "3838"
  caddy:
    image: caddy:2.3.0-alpine
    restart: always
    ports:
      - "3839:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - $PWD/log:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - solar
    environment:
      - HOST=":80"
      - EMAIL="your.name@yourdomain.com"
volumes:
  caddy_data:
  caddy_config:
